title: Dora Zhang
logo: "/images/Profile Pic.jpg?raw=true"
description: 
  MS in Applied Data Science Candidate
  University of St. Thomas
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
